export enum IOMsg{
	EMPTY = "",
	OK = "Operation successful!",
	LOGOUT = "Logout successful!",
	ERROR_BODY = "Something went wrong, please try again later!",
	DATA_POPULATE_SUCCESSFULLY = "Data populate successfully on spread sheet!",
	USER_EXIST = "User already exist!",
	USER_FOUND = "User found!",
	USER_NOT_FOUND = "User not found!",
	LOGIN_SUCCESS = "Login successful!",
	REGISTRATION_SUCCESS = "Registration successful!",
	LOGIN_UNSUCCESSFUL = "Login unsuccessful!",
	REGISTRATION_UNSUCCESSFUL = "Registration unsuccessful!",
	JWT_ERROR = "JWT token missing!",
	UPDATE_OK = "Update successful!",
	NOT_FOUND = "Not found!",
	LOADING_MSG = "Please wait....!",
	INIT_LOAD_MSG = "Initial data fetch successfully",
	SITE_SAVED = "Site saved successfully!",
	LOADING_HEAD = "LOADING",
	SUCCESS_HEAD = "SUCCESS",
	ERROR_HEAD = "ERROR",
}
